// AUTO-GENERATED by scripts/gen-licenses.mjs — 手で編集しない。
// 再生成: corepack pnpm licenses:gen
import type { LegalDocument } from "./legal";

export const THIRD_PARTY_LICENSES: LegalDocument = {
  title: "サードパーティライセンス",
  version: "2026-07-15",
  sections: [
  {
    "heading": "core-util-is 1.0.3 — MIT",
    "body": "Copyright: Isaac Z. Schlueter\nhttps://github.com/isaacs/core-util-is#readme"
  },
  {
    "heading": "idb 8.0.3 — ISC",
    "body": "Copyright: Jake Archibald\nhttps://github.com/jakearchibald/idb#readme"
  },
  {
    "heading": "immediate 3.0.6 — MIT",
    "body": "https://github.com/calvinmetcalf/immediate#readme"
  },
  {
    "heading": "inherits 2.0.4 — ISC",
    "body": "https://github.com/isaacs/inherits#readme"
  },
  {
    "heading": "isarray 1.0.0 — MIT",
    "body": "Copyright: Julian Gruber\nhttps://github.com/juliangruber/isarray"
  },
  {
    "heading": "jszip 3.10.1 — (MIT OR GPL-3.0-or-later)",
    "body": "Copyright: Stuart Knightley\nhttps://github.com/Stuk/jszip#readme"
  },
  {
    "heading": "lie 3.3.0 — MIT",
    "body": "https://github.com/calvinmetcalf/lie#readme"
  },
  {
    "heading": "lucide-react 1.24.0 — ISC",
    "body": "Copyright: Eric Fennis\nhttps://lucide.dev"
  },
  {
    "heading": "pako 1.0.11 — (MIT AND Zlib)",
    "body": "https://github.com/nodeca/pako"
  },
  {
    "heading": "process-nextick-args 2.0.1 — MIT",
    "body": "https://github.com/calvinmetcalf/process-nextick-args"
  },
  {
    "heading": "react 19.2.7 — MIT",
    "body": "https://react.dev/"
  },
  {
    "heading": "react-dom 19.2.7 — MIT",
    "body": "https://react.dev/"
  },
  {
    "heading": "readable-stream 2.3.8 — MIT",
    "body": "https://github.com/nodejs/readable-stream#readme"
  },
  {
    "heading": "safe-buffer 5.1.2 — MIT",
    "body": "Copyright: Feross Aboukhadijeh\nhttps://github.com/feross/safe-buffer"
  },
  {
    "heading": "scheduler 0.27.0 — MIT",
    "body": "https://react.dev/"
  },
  {
    "heading": "setimmediate 1.0.5 — MIT",
    "body": "Copyright: YuzuJS\nhttps://github.com/YuzuJS/setImmediate#readme"
  },
  {
    "heading": "string_decoder 1.1.1 — MIT",
    "body": "https://github.com/nodejs/string_decoder"
  },
  {
    "heading": "util-deprecate 1.0.2 — MIT",
    "body": "Copyright: Nathan Rajlich\nhttps://github.com/TooTallNate/util-deprecate"
  }
],
};
